Name:           ros-melodic-four-wheel-steering-controller
Version:        0.14.2
Release:        0%{?dist}
Summary:        ROS four_wheel_steering_controller package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/four_wheel_steering_controller
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-melodic-controller-interface
Requires:       ros-melodic-four-wheel-steering-msgs
Requires:       ros-melodic-nav-msgs
Requires:       ros-melodic-realtime-tools
Requires:       ros-melodic-tf
Requires:       ros-melodic-urdf-geometry-parser
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-controller-interface
BuildRequires:  ros-melodic-controller-manager
BuildRequires:  ros-melodic-four-wheel-steering-msgs
BuildRequires:  ros-melodic-nav-msgs
BuildRequires:  ros-melodic-realtime-tools
BuildRequires:  ros-melodic-rosgraph-msgs
BuildRequires:  ros-melodic-rostest
BuildRequires:  ros-melodic-std-srvs
BuildRequires:  ros-melodic-tf
BuildRequires:  ros-melodic-urdf-geometry-parser

%description
Controller for a four wheel steering mobile base.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Tue Oct 23 2018 Vincent Rousseau <vincent.rousseau@irstea.fr> - 0.14.2-0
- Autogenerated by Bloom

* Tue Jun 26 2018 Vincent Rousseau <vincent.rousseau@irstea.fr> - 0.14.1-0
- Autogenerated by Bloom

* Fri Apr 27 2018 Vincent Rousseau <vincent.rousseau@irstea.fr> - 0.14.0-0
- Autogenerated by Bloom

