Name:           ros-lunar-four-wheel-steering-controller
Version:        0.13.2
Release:        0%{?dist}
Summary:        ROS four_wheel_steering_controller package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/four_wheel_steering_controller
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-lunar-controller-interface
Requires:       ros-lunar-four-wheel-steering-msgs
Requires:       ros-lunar-nav-msgs
Requires:       ros-lunar-realtime-tools
Requires:       ros-lunar-tf
Requires:       ros-lunar-urdf-geometry-parser
BuildRequires:  ros-lunar-catkin
BuildRequires:  ros-lunar-controller-interface
BuildRequires:  ros-lunar-controller-manager
BuildRequires:  ros-lunar-four-wheel-steering-msgs
BuildRequires:  ros-lunar-nav-msgs
BuildRequires:  ros-lunar-realtime-tools
BuildRequires:  ros-lunar-rostest
BuildRequires:  ros-lunar-std-srvs
BuildRequires:  ros-lunar-tf
BuildRequires:  ros-lunar-urdf-geometry-parser

%description
Controller for a four wheel steering mobile base.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lunar/setup.sh" ]; then . "/opt/ros/lunar/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/lunar" \
        -DCMAKE_PREFIX_PATH="/opt/ros/lunar" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lunar/setup.sh" ]; then . "/opt/ros/lunar/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/lunar

%changelog
* Sat Dec 23 2017 Vincent Rousseau <vincent.rousseau@irstea.fr> - 0.13.2-0
- Autogenerated by Bloom

