Name:           ros-kinetic-four-wheel-steering-controller
Version:        0.13.3
Release:        0%{?dist}
Summary:        ROS four_wheel_steering_controller package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/four_wheel_steering_controller
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-kinetic-controller-interface
Requires:       ros-kinetic-four-wheel-steering-msgs
Requires:       ros-kinetic-nav-msgs
Requires:       ros-kinetic-realtime-tools
Requires:       ros-kinetic-tf
Requires:       ros-kinetic-urdf-geometry-parser
BuildRequires:  ros-kinetic-catkin
BuildRequires:  ros-kinetic-controller-interface
BuildRequires:  ros-kinetic-controller-manager
BuildRequires:  ros-kinetic-four-wheel-steering-msgs
BuildRequires:  ros-kinetic-nav-msgs
BuildRequires:  ros-kinetic-realtime-tools
BuildRequires:  ros-kinetic-rosgraph-msgs
BuildRequires:  ros-kinetic-rostest
BuildRequires:  ros-kinetic-std-srvs
BuildRequires:  ros-kinetic-tf
BuildRequires:  ros-kinetic-urdf-geometry-parser

%description
Controller for a four wheel steering mobile base.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Fri Apr 27 2018 Vincent Rousseau <vincent.rousseau@irstea.fr> - 0.13.3-0
- Autogenerated by Bloom

* Sat Dec 23 2017 Vincent Rousseau <vincent.rousseau@irstea.fr> - 0.13.2-0
- Autogenerated by Bloom

